# SPDX-FileCopyrightText: Copyright (c) 2022 Neradoc, https://neradoc.me
# SPDX-License-Identifier: CC0-1.0
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
